version: '3'
services:
  daemon:
    image: 'nextcloud:16'
    hostname: cloud.domain.net
    volumes:
      - ${CLOUD_VOLUME_CONFIG:-./volumes/config}:/var/www/html/config
      - ${CLOUD_VOLUME_DATA:-./volumes/data}:/var/www/html/data
      - ${CLOUD_VOLUME_APPS:-./volumes/apps}:/var/www/html/apps
      - ${CLOUD_VOLUME_CUSTOM_APPS:-./volumes/custom_apps}:/var/www/html/custom_apps
      - ${CLOUD_VOLUME_THEMES:-./volumes/themes}:/var/www/html/themes
    networks:
      - web
      - databases
      - default
    environment:
      - TZ=Lisbon
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:cloud.domain.net"
        - "traefik.frontend.port=80"
  cache:
    image: 'redis'
    volumes:
      - ${CLOUD_VOLUME_CACHE:-./volumes/cache}:/data
networks:
  web:
    external: true
  databases:
    external: true
