version: '3'
services:
  daemon:
    image: 'lsioarmhf/nextcloud'
    volumes:
      - ./volumes/config:/config
      - ./volumes/data:/data
    networks:
      - web
      - databases
      - default
    environment:
      - TZ=Lisbon
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.protocol=https"
        - "traefik.port=443"
        - "traefik.frontend.rule=Host:cloud.zalkeen.net"
        - "traefik.frontend.port=443"
networks:
  web:
    external: true
  databases:
    external: true
